### ISSUE TITLE
Suggestion: Use .html() instead of .text()

### ISSUE THREAD

**Issue by kaiga747** [micc83/ReStable#5]
In most cases we would want to get all links and form elements cascaded into table cells.

**Comment by jelewis8** [comment]
Image tags seem to get stripped out. I have keepHtml set to true.
Any ideas?

**Comment by micc83** [comment]
Using version 0.1.2? Could you make an example on http://jsfiddle.net/ ?

**Comment by jelewis8** [comment]
Sorry, been out of the loop, just now saw this!

Here's a fiddle of it: http://jsfiddle.net/96ap2c27/2/

**Comment by micc83** [comment]
Hello @jelewis8, check issue #8, it might be the same issue.

**Comment by jelewis8** [comment]
I tried to follow what the problem was in that other thread but couldn't make it out.
I'm using 0.1.2. Did you see my fiddle? http://jsfiddle.net/96ap2c27/2/

**Comment by jelewis8** [comment]
AHH, NM. Just set rowheader to false and that seems to fix the issue.

Though I'm still not sure why.

**Comment by micc83** [comment]
Hello @jelewis8, I'll make sure to check it out before releasing 0.1.2. 
Thank you
