### ISSUE TITLE
Images are absent in list

### ISSUE THREAD

**Issue by KingR1** [micc83/ReStable#8]
In table in column i have just images. When i applied ReStable-plugin this images are absent in lists.

<ul>
   <li class="cf">
      <span class="row_headers">
	 3D Streets of Rage
      </span> <span class="row_data ">&nbsp;</span></li><li class="cf"><span class="row_headers">
										Nintendo 3DS
									</span> <span class="row_data ">
										 
									</span></li><li class="cf"><span class="row_headers">
										<-- here must be image
									</span> <span class="row_data "></span></li><li class="cf"><span class="row_headers">
										Fantasy Violence
									</span> <span class="row_data "></span></li><li class="cf"><span class="row_headers">
										None
									</span> <span class="row_data "></span></li><li class="cf"><span class="row_headers">
										Sega
									</span> <span class="row_data "></span></li></ul>
______________________________________
<table class="table" id="10002649">
								<tr>
									<td>
										<strong name="title">3D Streets of Rage</strong>
									</td>
									<td>
										Nintendo 3DS
									</td>
									<td>
										<img alt="Rating" src="http://localhost:9450/content/Images/E10plus.png">
									</td>
									<td>
										Fantasy Violence
									</td>
									<td>
										None
									</td>
									<td>
										Sega
									</td>
								</tr>
						</table>

**Comment by micc83** [comment]
Have you been using ReStable 1.0.2 ?! https://github.com/micc83/ReStable/tree/v0.1.2
Moreover, if i'm not wrong even on 1.0.2 html should be allowed only on td not th.
Let me know,
Alex

**Comment by KingR1** [comment]
@micc83 Hi! Firstly i tried with 1.0.1 version, then with 1.0.2 but i include them as links.

About `<th>` - i didn't post html table example with images in th, just in td. I will try to update example to make it work

**Comment by micc83** [comment]
Can you recreate the example on http://jsfiddle.net/ ?

**Comment by KingR1** [comment]
@micc83 Please, http://jsfiddle.net/qxp777f4/

**Comment by micc83** [comment]
Hi @KingR1 what i meant was to recreate the working example. Not only the result... :smile:

**Comment by KingR1** [comment]
@micc83 http://jsfiddle.net/qxp777f4/1/ I include 1.0.1 version, but now <ul> is empty

**Comment by KingR1** [comment]
@micc83 this one is with 1.0.2 http://jsfiddle.net/qxp777f4/2/

**Comment by micc83** [comment]
I don't know where the problem was however it seems to work fine: http://jsfiddle.net/qxp777f4/5/

**Comment by KingR1** [comment]
@micc83 Here http://jsfiddle.net/qxp777f4/6/ i left my html table + add table `head` + add all your scripts from your example... And it doesn't work :(

**Comment by micc83** [comment]
Hi @KingR1,

I checked, the problem is with jsfiddle that doesn't send the resize event. Resize manually the preview screen then run the script again. It will work. Or simply try locally.
